[package]
name = "rustic"
version = "0.1.0"
authors = ["veaba <godpu@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex="1"
