# like nginx config
# TODO: Use toml file it is correct as config? maybe think about it!
# TODO: Support native nginx.conf, maybe it's a good idea.
# TODO: http、server、location、upstream、event、main

# config="config.toml"
[base]
config_path="config.toml"
access_log=true # default true, {bool}
error_log=true # default true, {bool}

# security
[security]
key="key.key"
cert="cert.pem"

# Http
[http]
[[http.server]]
port=80
server_name="localhost"
gzip="on" #default on, {on,off}
root="./html/index.html"
server_root="./html/500.html"
client_root="./html/400.html"
index=["index.html","index.htm","index.php"]
[[http.server]]
port=81
server_name="localhost"
gzip="on" #default on, {on,off}
root="./html/index.html"
server_root="./html/500.html"
client_root="./html/400.html"
index=["index.html","index.htm","index.php"]


# TODO How toml file match the regex?
# Proxy
[proxy]
api="http://127.0.0.1:8081"   # 127.0.0.1/api/        => 127.0.0.1:8081/api/
#api.user="http/127.0.0.1:8082" # 127.0.0.1/api/user    => 127.0.0.1:8082/api/user
"/dsa/"="ds"

# Logs
[logs]
access="logs/access.log"
error="logs/error.logs"
